### ISSUE TITLE
Setup repo to allow for local development without AWS

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#105]
**Overview**
> Technical stack for this work: Python, FastAPI, React

Currently it's challenging for developers to setup akello locally for full end-to end development since it requires AWS service to run (AWS Cognito & DynamoDB). We need to allow developers to run the server locally without needing an AWS account.

DynamoDB has a local environment but there isn't a free option for AWS Cognito. To make this possible we will need to allow for multiple authentication methods. This will require an update on the Fast API server as well as the the React app.

## Technical requirements

**Fast API**
Allow Fast API Server to be configured with multiple auth providers, for now we just need AWS Cognito and a local Auth (e.g., username/password). The database for the local auth would need to be in sqlite.

**Client**
The client will need UI components to handle the auth. Currently its configured with AWS Amplify's Authenticator: ref: https://ui.docs.amplify.aws/react/connected-components/authenticator

You can view a working demo of the app at **https://demo.akello.io**

## Acceptance criteria
* A developer can set a config flag locally to use the local environment
* A developer does not need an AWS account to contribute code
* A developer can implement multiple auth providers if they wish (keep this in mind when implementing/designing)
* The React App has a component that allows a user to Sign-up/Login using the local auth method
* API's should be consumed with token based auth
* A developer can run this repo locally, make updates to data and have everything persisted. They should be able to shutdown their environment and login later.
* Clear documentation is provided so a developer can setup akello's repo and run locally

## Notes
* Server auth code: https://github.com/akello-io/akello/tree/main/server/akello/auth
* Demo app auth code: https://github.com/akello-io/akello/blob/main/apps/cocm-registry/src/App.tsx#L80
* Sample login page: https://github.com/akello-io/akello/blob/main/apps/akello-app/src/containers/pages/public/Login.tsx

I am working on refactoring out cocm-registry into akello-app which will leverage the new akello react component library. If you wish, you can create another app under /examples. From there post your working example of using the local-auth for dev and also how that would switch to use another auth provider like AWS Cognito

**Comment by rishi-raj-jain** [comment]
@neo773 is fast.

**Comment by vselvarajijay** [comment]
Btw - we do have a discord server [here](https://discord.gg/xYpwZCTv). Feel free to join if you need any fast responses or need to discuss anything.
