### ISSUE TITLE
UX Design: Clean up Patient Information section on the patient treatment bar

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#12]
<img width="729" alt="Screenshot 2023-10-31 at 9 26 21 PM" src="https://github.com/akello-io/akello/assets/398292/5aef9c73-4fe6-459f-b34d-e40780b911f0">

**Comment by vselvarajijay** [comment]
Hey @Min2who - I don't have a directional UI, but this is breaking some consistency.. Vertical spacing, the format of the dropdown buttons.. 

Tailwind has some examples where the spacing looks right: https://tailwindui.com/components/application-ui/data-display/description-lists

If we can follow tailwind as a base I think it would put us in a good direction 

If you have any thoughts on layout structure, feel free to take a stab at it

You can try out the demo here: https://demo.akello.io.. You will need to do the following
1. Sign up
2. Create a registry
3. Add a patient
3. Click on the patient to view the slide out drawer shown for this ticket

**Comment by vselvarajijay** [comment]
@Min2who -- we do have a discord server [here](https://discord.gg/xYpwZCTv). Feel free to join if you need any fast responses or need to discuss anything.

**Comment by Min2who** [comment]
sure

**Comment by Min2who** [comment]
i will solve this issue in a week or two 
P.S:am occupied a bit with my exams lately

**Comment by vselvarajijay** [comment]
@Min2who - let me know if you would still like to work on this issue
