### ISSUE TITLE
Billing report needs a spinner/loader when pulling data from the server

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#14]
<img width="721" alt="Screenshot 2023-10-31 at 9 33 36 PM" src="https://github.com/akello-io/akello/assets/398292/aa29c70f-474a-420b-86a2-6aa1a1d2f2c9">

**Comment by vselvarajijay** [comment]
Hey - for sure! Let me know if you need any help getting the environment up and running. I am working on the docs now

**Comment by vselvarajijay** [comment]
Here is an example of running the API server: https://github.com/akello-io/akello/tree/main/examples/foo-api. Unfortunately I don't have a. way to run aws cognito locally just yet, I will create a ticket for it.

**Comment by iDK-pseudo** [comment]
Hi Vijay, I was trying to setup the env yesterday, was able to do it for client but the server was throwing some error. Let me check your example and get back to you if any help is needed.

Thanks

**Comment by vselvarajijay** [comment]
Sounds good @iDK-pseudo, I will keep this ticket assigned to you as you investigate it. Please let me know if you have any issues. If you don't have AWS I might need to figure out a way to get the AWS Cognito Auth working locally

**Comment by vselvarajijay** [comment]
I added an initial working version of a mock server to run the react apps. You can follow the instructions here to get started. I hope that works and gets you up and running!

**Comment by iDK-pseudo** [comment]
Hi Vijay, tried setting up the mockserver as mentioned but I am getting CORS error in the network calls for the [URL](http://localhost:8000/mockserver/v1/user/registries)

I made one mockserver.properties file and that seems to be have resolved CORS error but now I am getting 404 not found on the same URL. Can you let me know what could be the reason ? Is the mockserver working fine for you ?

**Comment by vselvarajijay** [comment]
@iDK-pseudo sorry for the delay. We have a new way of setting up the local environment with AWS Cognito mocked along with AWS DynamoDB in a docker container. Let me know if you would still like to work on this
