### ISSUE TITLE
Storybook build showing a blank site

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#160]
When creating a build for a storybook under `packages/react` the site is blank. Probably a configuration issue with storybook and the packages installed with it.

```shell
cd packages/react
npm run storybook     <--- not empty

npm run build-storybook
npx http-server storybook-static     <--- empty site
```

**Comment by vselvarajijay** [comment]
@Akshay-SL  feel free to join the discord server over here if you would like to chat: https://discord.gg/WSqNrWBKKw

**Comment by rajdip-b** [comment]
@Akshay-SL hey, are you still attempting this one? I feel I have found a workaround, so would like to take this up just in case.
