### ISSUE TITLE
Bug: Cannot read properties of null (reading 'useContext')

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#197]
<img width="1119" alt="Screenshot 2024-01-28 at 9 38 09 PM" src="https://github.com/akello-io/akello/assets/398292/db421595-22e8-4732-a320-b37383d76206">

# Steps to reproduce the bug:

### To setup your local dev:
1. python scripts/akello.py setup (set your environment variables)
2. python scripts/akello.py start server
3. python scripts/akello.py start cocm (in another terminal)

### Create a user account 
* SMS Code verification is `1234`

### Login and reproduce the bug
* Login
* Create a registry
* Navigate to the registry <== you should now see the bug

**Comment by vselvarajijay** [comment]
@rajdip-b

**Comment by rajdip-b** [comment]
You can assign this to me!

**Comment by jemiluv8** [comment]
still up for grabs?

**Comment by rajdip-b** [comment]
> still up for grabs?

Hey @jemiluv8, I have been wokring on it for some time now :)

**Comment by vselvarajijay** [comment]
To join the discussion on this PR feel free to join the Discord server https://discord.gg/p27Dg7u2

The conversation is under a thread in #development with the ticket number referred 

@rajdip-b @chnrv99 @jemiluv8

**Comment by vselvarajijay** [comment]
> > still up for grabs?
> 
> 
> 
> Hey @jemiluv8, I have been wokring on it for some time now :)

@rajdip-b - Make sure to use /attempt to mark that you started working on this

**Comment by vselvarajijay** [comment]
Resolved by this PR: https://github.com/akello-io/akello/pull/198
