### ISSUE TITLE
Bug: Unable to use react hooks under @akello/react package 

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#200]
When trying to add useState inside any component under `packages/react` from the `apps/cocm-registry` app the following error occurs. This issue is related to [issue-197](https://github.com/akello-io/akello/issues/197), however that specific case was resolved. This one is to ensure any component under `packages/react` can leverage react hooks

![image](https://github.com/akello-io/akello/assets/398292/77017ab7-e65e-4030-8d08-58e7bb72d4ae)

# Steps to setup and run the app:

### To setup your local dev:
1. python scripts/akello.py setup (set your environment variables)
2. python scripts/akello.py start server
3. python scripts/akello.py start cocm (in another terminal)

### Create a user account 
* SMS Code verification is `1234`

### Login and reproduce the bug
* Login
* Create a registry

# Acceptance criteria:
* **[Required]** Update ThemeSwap component to use state: [TemeSwap Component](https://github.com/akello-io/akello/tree/main/packages/react/src/react-core/01_atoms/ThemeSwap). You can use this reference to build the component: [example](https://stackoverflow.com/questions/72926946/how-can-i-change-themes-using-daisyui-and-tailwindcss-in-a-react-project). The component should be added to the following section in CoCM Registry: [Test Section](https://github.com/akello-io/akello/blob/main/apps/cocm-registry/src/apps/registry_list/RegistrySelector.tsx#L145)
* **[Required]** A developer should be able to add react hooks (e.g., useState, useEffect, etc.) to components under packages/react and be imported into apps/cocm-registry to be used

# Discord
Feel free to join the discord server there if you would like to discuss this issue: https://discord.gg/WSqNrWBKKw. A thread has been created `#development --> GH - #200`

**Comment by rajdip-b** [comment]
I'll try to look into this today.
