### ISSUE TITLE
main image on homepage

### ISSUE THREAD

**Issue by jmb1993001** [akello-io/akello#448]
The primary image at the top of the homepage is a bit cut off on my browser (not sure if this is specific to me) - see attached screenshot . Ideally it would be centered so the entire image is visible. 
<img width="1279" alt="Screen Shot 2024-03-26 at 3 52 54 PM" src="https://github.com/akello-io/akello/assets/163335810/a34ca45b-f670-4ec5-8e65-0c47943f6860">

**Comment by vselvarajijay** [comment]
Yeah this is currently a design decision. It opens up on larger screens. The intent here is to keep a big image while not collapsing the main copy
