### ISSUE TITLE
Account Microservice User API Endpoints

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#650]
**User Endpoint**

`POST /v1/user/`
- Create new user 

`GET /v1/user/{user_id}/`
- Get user - returns JSON object of the User resource

`PUT /v1/user/{user_id}/`
- Update user  - PUT a JSON object and the backend should do a lookup and make updates only by key/value

----

QA Notes:

- Need to validate that the email post is a valid email
- Need to handle cases if a user already exists
- Need to handle cases if a user does not exist

**Comment by vselvarajijay** [comment]
Tagging @matthewhou19  since he is working on this

**Comment by matthewhou19** [comment]
'I will work on it
