### ISSUE TITLE
FHIR QuestionnaireResponse -> react-fhir component

### ISSUE THREAD

**Issue by vselvarajijay** [akello-io/akello#99]
Design and create a react component under the react-fhir npm package modeled after the QuestionnaireResponse FHIR resource.

## Interface

**Sample interface contract**

```
<QuestionnaireResponse fhir-resource={data} />
```

That should now render a QuestionnaireResponse. If the user provided answers then it should show just the questionnaire response else it should render inputs to provide responses.

##   Styling

We would need to add in a prop to help inform the style and theme of the component.. also the layout

**Comment by ninar12** [comment]
I can work on this!

**Comment by vselvarajijay** [comment]
I just noticed that there is a github repo here to consider https://github.com/1uphealth/fhir-react#readme
